### ISSUE TITLE
Package 'ssvd' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/NumericalMathematics#7]
Package [ssvd](https://CRAN.R-project.org/package=ssvd) is currently listed in CRAN Task View [NumericalMathematics](https://CRAN.R-project.org/view=NumericalMathematics) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by hwborchers** [comment]
CRAN has archived the following packages on our NumericalMathematics task View
(with year of last update):

    2019  chebpoly
    2012  eigeninv
    2013  ssvd

I'd suggest removing the two ten year old packages from the task view as I don't expect them to return to CRAN anyway. I think with 'chebpoly' we can wait a bit.

**Comment by hwborchers** [comment]
Archived package 'ssvd' has been removed from the Task View.
